package com.amazonaws.comprehend.esproxy.lambda.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * The BulkRequest generated by each BulkPayload
 */
@AllArgsConstructor
@Getter
public class BulkRequest {
    private final String fieldToBeComprehend;

    private final ComprehendOperationEnum comprehendOperation;

    private final LanguageCode languageCode;

    private final BatchFieldLocator locator;
}
